### ISSUE TITLE
Odd bug in combination with MathJax

### ISSUE THREAD

**Issue by ghost** [arturadib/strapdown#20] opened 2013-06-14 13:30 UTC
strapdown and MathJax usually work perfectly together, but not with an expression like:
`$$a_n \sum_{i}$$`
The problems seems to be ther {} around the i. Without, it works. Also without the a_n before it does (even with the {}'s).  Strange problem since both of these Versions work:
`$$a \sum_{i}$$`
`$$a_n \sum_i$$`
Same problem with \prod instead of \sum by the way. The problem doesn't lie with MathJax, I checked.

edit: minimal example: http://leastaction.org/strapdown_bug.html

**Comment by memeplex** [comment] 2013-08-09 13:58
This is not a bug. Just look at the output of marked for your markdown:

marked(markdown)
=>
`<ul><li>works: $$a \sum_{i}$$</li><li>works: $$a_n \sum_i$$</li><li>doesn&#39;t: $$a<em>n \sum</em>{i}$$</li></ul>`

Do you see the <em>'s? Now read http://daringfireball.net/projects/markdown/syntax#em and you will understand.

You just need to escape special characters sometimes: http://daringfireball.net/projects/markdown/syntax#backslash.

Please close this one.

**Closed as completed** 2013-11-26 01:14 UTC
